// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hit } from "./Hit";
import type { Links } from "./Links";

export interface EdamamResponse { from: bigint, to: bigint, count: bigint, _links: Links | null, hits: Array<Hit>, }