// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Links2 } from "./Links2";
import type { Recipe } from "./Recipe";

export interface Hit { recipe: Recipe, _links: Links2, isScrapable: boolean | null, isValid: boolean | null, }