// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Image } from "./Image";

export interface Images { THUMBNAIL: Image | null, SMALL: Image | null, REGULAR: Image | null, LARGE: Image | null, }