// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Ingredient { text: string | null, quantity: number | null, measure: string | null, food: string | null, weight: number | null, foodCategory: string | null, foodId: string | null, image: string | null, }