// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecipeDetails { image: string, url: string, servings: number, time: number, calories: number, source: string | null, ingredients: Array<string> | null, instructions: Array<string> | null, title: string, id: number | null, date_added: string | null, }