// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Sub { label: string | null, tag: string | null, schemaOrgTag: string | null, total: number | null, hasRDI: boolean | null, daily: number | null, unit: string | null, }